# Generated by Django 5.1.2 on 2024-10-26 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='edues/%Y/%m')),
                ('category_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edues.category')),
            ],
        ),
    ]
