# Generated by Django 5.1.2 on 2024-10-26 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edues', '0002_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('subject', 'category_fk')},
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acctive', models.CharField(max_length=50, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='lesson/%Y/%m')),
                ('lesson_fk', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='edues.course')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
