"""
Django settings for eduappes project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent  # cái này là nó tự tạo mặc định luôn trỏ tới project

# Nhớ phải là tên app hay static nằm chung với mirgrations
MEDIA_ROOT = '%s/edues/static/' % BASE_DIR

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a0(zj2)m=ojxu^%tly4%2klr^c3)7e^fwh)$!$#!baqz6s0ufk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #     Khai báo app mới ở dưới đây
    'edues',
    # or 'edues.apps.EduesConfig(AppConfig)'
    # thêm vào để textfilder soạn thảo văn bản oke thêm xong nhớ phẩy
    'ckeditor',
    'ckeditor_uploader',
]

# Xong rồi qua bên urls của eduappes cập nhật urlpartteerns
AUTH_USER_MODEL = 'edues.User'
#Cập nhật thêm cho biến này cho ckeditor -> tên lesson phải đúng với một bảng nào đó -> vd nhu category
CKEDITOR_UPLOAD_PATH = "images/ckeditor/"
import pymysql

pymysql.install_as_MySQLdb()
# cài xong rồi chạy Lệnh makemigrations

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'eduappes.urls'
# Thêm dòng này import os
import os
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':  [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            #Tạo thu muc templates trong edues roi them nay vao
            ],
        },
    },
]

WSGI_APPLICATION = 'eduappes.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        # copy tu slide
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'edu_manage',  # tenCSDL mySQL
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': ''  # mặc định localhost
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/



#Thêm đường dẫn này để link index.css
# Đường dẫn cho các file tĩnh cấp project
# Đảm bảo rằng phần cấu hình này có trong settings.py
# Cấu hình đường dẫn để Django tìm thư mục static của các ứng dụng\

STATIC_URL = '/static/'

# Đường dẫn đến thư mục chứa các file tĩnh (nằm trong app edues)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'edues', 'static'),
]
# Cấu hình đường dẫn để Django tìm thư mục static của các ứng dụng


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
